name: uModDetect
version: '0.1'
main: one.yuqas.Main
api-version: '1.20'
authors: [ 1Yuqas ]
description: Detects specific client-side mods using hidden sign-based translation packets.
commands:
  umd:
    usage: /umd reload"
    permission: umd.command

permissions:
  umd.command:
    description: uModDetect command permission.
    default: op
  umd.message:
    description: uModDetect message permission for custom messages.
    default: op
